[package]
name = "second-brain"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "data-importers/markdown-parser"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]